"""Gas-phase transport. Replaces READ_GAS, the gas property functions
(CALC_GCP, CALC_GMU, CALC_RGAS, CALC_HGAS, CALC_HGAS_ABS, CALC_UGAS,
CALC_RHOG, CALC_RHOGP, CALC_CVG), SOLVE_GAS, and TRIDIG in 1Dheat.f.

The gas table (gas_props.dat) has columns:
    T [K], M_mix [kg/kmol], cp [J/kg/K], mu [Pa s], h [J/kg], rho_1atm
The specific gas constant is R = R_universal / M.

SOLVE_GAS is a steady Darcy pressure solve each timestep: gas generated by
pyrolysis (gsrc) minus storage (porosity*rho_gas change) drives a flux
through a permeability-weighted conductance CFACE. With a sealed back
(gbnd0=0) and an open front (gbndn=1) the system is explicit; other BC
combinations need the tridiagonal solve.

All property functions accept scalar or ndarray T and clamp at the table
ends, matching the Fortran cached-index linear interpolation.
"""

from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .case import Case
from .domain import Domain
from .pyrolysis import SolidParams

R_UNIVERSAL = 8314.46261815324  # J/kmol/K


@dataclass
class GasTable:
    """Temperature-indexed gas mixture properties (gas_props.dat)."""
    T: np.ndarray        # (N,) temperatures [K]
    R: np.ndarray        # (N,) specific gas constant R_univ/M [J/kg/K]
    cp: np.ndarray       # (N,) heat capacity [J/kg/K]
    mu: np.ndarray       # (N,) dynamic viscosity [Pa s]
    h: np.ndarray        # (N,) absolute enthalpy [J/kg]
    rho: np.ndarray      # (N,) density at 1 atm [kg/m^3]


def load_gas_table(path: str | Path) -> GasTable | None:
    """Parse gas_props.dat. Returns None if the file is absent (NBRGAS=0
    in the Fortran, which makes every gas property fall back to its scalar
    CASE_* value)."""
    p = Path(path)
    if str(path).strip() == "" or not p.exists():
        return None
    data = np.loadtxt(str(p), comments=("#", "!"))
    if data.ndim != 2:
        data = data.reshape(1, -1)
    mw = data[:, 1]
    return GasTable(
        T=data[:, 0].astype(np.float64),
        R=R_UNIVERSAL / np.maximum(mw, 1.0e-12),
        cp=data[:, 2].astype(np.float64),
        mu=data[:, 3].astype(np.float64),
        h=data[:, 4].astype(np.float64),
        rho=data[:, 5].astype(np.float64),
    )


# ----------------------- Gas property lookups ----------------------- #
# np.interp clamps to the table endpoints, exactly like the Fortran
# CALC_* functions' below-first / above-last branches.


def _ref_temp(case: Case) -> float:
    tref = case.init_temp
    if case.hgas_tref > 0.0:
        tref = case.hgas_tref
    return tref


def calc_gcp(T, gas: GasTable | None, case: Case):
    if gas is None:
        return np.full_like(np.asarray(T, dtype=float), case.gcp)
    return np.interp(T, gas.T, gas.cp)


def calc_gmu(T, gas: GasTable | None, case: Case):
    if gas is None:
        return np.full_like(np.asarray(T, dtype=float), case.gmu)
    return np.interp(T, gas.T, gas.mu)


def calc_rgas(T, gas: GasTable | None, case: Case):
    if gas is None:
        return np.full_like(np.asarray(T, dtype=float), case.rgas)
    return np.interp(T, gas.T, gas.R)


def calc_hgas_abs(T, gas: GasTable | None, case: Case):
    """Absolute gas enthalpy at T (no reference subtraction)."""
    if gas is None:
        return np.zeros_like(np.asarray(T, dtype=float))
    return np.interp(T, gas.T, gas.h)


def calc_hgas(T, gas: GasTable | None, case: Case):
    """Gas enthalpy relative to the reference temperature."""
    if gas is None:
        return np.zeros_like(np.asarray(T, dtype=float))
    href = np.interp(_ref_temp(case), gas.T, gas.h)
    return np.interp(T, gas.T, gas.h) - href


def calc_ugas(T, gas: GasTable | None, case: Case):
    """Gas internal energy: h(T) - (R(T)*T - R(Tref)*Tref)."""
    tref = _ref_temp(case)
    rref = calc_rgas(tref, gas, case)
    return calc_hgas(T, gas, case) - (calc_rgas(T, gas, case) * np.asarray(T)
                                      - rref * tref)


def calc_rhogp(T, P, gas: GasTable | None, case: Case):
    """Ideal-gas density from pressure: P / (R(T) * max(T, 250))."""
    R = calc_rgas(T, gas, case)
    return np.maximum(P, 1.0e-30) / np.maximum(
        R * np.maximum(T, 250.0), 1.0e-30)


def calc_cvg(T, gas: GasTable | None, case: Case):
    """Gas isochoric heat capacity: cp(T) - R(T)."""
    return np.maximum(1.0e-6, calc_gcp(T, gas, case) - calc_rgas(T, gas, case))


def _porosity_array(rho: np.ndarray, rhov_b: float, rhoc_b: float,
                    case: Case, solid: SolidParams) -> np.ndarray:
    """Vectorized CALC_POROSITY over a 1D density array."""
    beta = np.clip((rhov_b - rho) / max(rhov_b - rhoc_b, 1.0e-30), 0.0, 1.0)
    poro = solid.phi + (case.phi_c - solid.phi) * beta
    phi_min = min(solid.phi, case.phi_c)
    phi_max = max(solid.phi, case.phi_c)
    poro = np.clip(poro, phi_min, phi_max)
    return np.clip(poro, 1.0e-6, 0.99)


# ----------------------- Pressure / mass-flux solve ----------------------- #


def _tridig(a: np.ndarray, b: np.ndarray, c: np.ndarray,
            d: np.ndarray) -> np.ndarray:
    """Backward-elimination Thomas solver, a faithful port of TRIDIG
    (1Dheat.f). a/b/c are the sub/diagonal/super bands (length n), d the
    RHS. a[0] and c[n-1] are unused, as in the Fortran."""
    n = a.size
    TOL = 1.0e-290
    b = b.copy()
    d = d.copy()
    for j in range(n - 2, -1, -1):
        f = -c[j] / b[j + 1]
        b[j] = b[j] + f * a[j + 1]
        d[j] = d[j] + f * d[j + 1]
        if -TOL < d[j] < TOL:
            d[j] = TOL if d[j] >= 0.0 else -TOL
    x = np.empty(n)
    x[0] = d[0] / b[0]
    for j in range(1, n):
        x[j] = (d[j] - a[j] * x[j - 1]) / b[j]
        if -TOL < x[j] < TOL:
            x[j] = TOL if x[j] >= 0.0 else -TOL
    return x


def solve_gas(T: np.ndarray, rho_old: np.ndarray, rho_new: np.ndarray,
              gsrc: np.ndarray, rhogsto: np.ndarray, pg: np.ndarray,
              pamb: float, dt: float, case: Case, domain: Domain,
              solid: SolidParams, gas: GasTable | None
              ) -> tuple[np.ndarray, np.ndarray]:
    """Solve the Darcy gas-pressure field and face mass fluxes for one step.

    Args (T and density arrays are (n+2,) with ghosts at 0 and n+1):
        T:        cell temperatures
        rho_old:  bulk density before this step's pyrolysis (RHO)
        rho_new:  bulk density after this step's pyrolysis (RHON)
        gsrc:     (n,) pyrolysis gas source for interior cells [kg/m^3/s]
        rhogsto:  (n,) stored gas density from the previous step
        pg:       (n+2,) gas pressure from the previous step
        pamb:     ambient pressure this step (CALC_AERO_P)
        dt:       timestep

    Returns:
        pg_new:   (n+2,) updated gas pressure
        mdotf:    (n+2,) face mass flux; entries 1..n+1 are the faces
    """
    n = domain.n_cells
    rhov_b = solid.rhov_bulk
    rhoc_b = solid.rhoc_bulk
    pmin = 1.0e-3 * pamb

    pg = pg.copy()
    pg[0] = pamb
    pg[n + 1] = pamb

    dx = domain.dx
    da = domain.da
    gradm = domain.gradm

    # --- Face conductances CFACE(I), I = 1..n+1 ---
    f = np.arange(1, n + 2)
    tface = T[f - 1] + (T[f] - T[f - 1]) * gradm[f]
    rho_face = 0.5 * (rho_new[f - 1] + rho_new[f])
    beta_face = np.clip((rhov_b - rho_face) / max(rhov_b - rhoc_b, 1.0e-30),
                        0.0, 1.0)
    k0 = np.maximum((1.0 - beta_face) * case.k0_v + beta_face * case.k0_c,
                    1.0e-30)
    mu = np.maximum(calc_gmu(tface, gas, case), 1.0e-30)
    pface = np.maximum(pmin, 0.5 * (pg[f - 1] + pg[f]))
    rhof = calc_rhogp(tface, pface, gas, case)
    cface = np.zeros(n + 2)
    cface[f] = k0 * rhof * da[f] / (mu * 0.5 * (dx[f - 1] + dx[f]))

    # --- Net gas source per interior cell (generation minus storage) ---
    ci = slice(1, n + 1)
    gnet = gsrc.copy()
    if dt > 0.0:
        por_new = _porosity_array(rho_new[ci], rhov_b, rhoc_b, case, solid)
        gstore = (por_new * calc_rhogp(T[ci], pg[ci], gas, case)
                  - rhogsto) / dt
        gnet = gnet - gstore

    dv = domain.dv[ci]
    mdotf = np.zeros(n + 2)

    if case.gbnd0 == 0 and case.gbndn == 1:
        # Sealed back, open front: explicit march, no linear solve.
        mdotf[2:n + 2] = np.cumsum(gnet * dv)            # MDOTF(1) = 0
        pg[n + 1] = pamb
        inc = np.zeros(n + 2)
        inc[f] = mdotf[f] / np.maximum(cface[f], 1.0e-30)
        # PG(I-1) = PG(I) + MDOTF(I)/CFACE(I): suffix sum marching front->back
        suffix = np.cumsum(inc[1:n + 2][::-1])[::-1]
        pg[0:n + 1] = pamb + suffix
        return pg, mdotf

    # --- General case: tridiagonal pressure solve ---
    a = -cface[1:n + 1].copy()              # a(I) = -CFACE(I)
    c = -cface[2:n + 2].copy()              # c(I) = -CFACE(I+1)
    b = (cface[1:n + 1] + cface[2:n + 2]).copy()
    d = -gnet * dv

    if case.gbnd0 == 1:
        d[0] = d[0] - a[0] * pamb
    else:
        b[0] = b[0] + a[0]
    if case.gbndn == 1:
        d[n - 1] = d[n - 1] - c[n - 1] * pamb
    else:
        b[n - 1] = b[n - 1] + c[n - 1]

    sol = _tridig(a, b, c, d)
    pg[1:n + 1] = np.maximum(pmin, sol)

    pg[0] = pamb if case.gbnd0 == 1 else pg[1]
    pg[n + 1] = pamb if case.gbndn == 1 else pg[n]

    mdotf[f] = -cface[f] * (pg[f] - pg[f - 1])
    if case.gbnd0 == 0:
        mdotf[1] = 0.0
    if case.gbndn == 0:
        mdotf[n + 1] = 0.0
    return pg, mdotf
